site_name: Meridian Universe
site_url: https://lentulus.github.io/MeridianUniverse/
nav:
  - Home: index.md
  - About: about.md
  - Projects:
    - AI Developed Software: Projects/AI.md
    - Meridian: Projects/meridian.md
    - Worlds: Projects/worlds.md
    - ColonyModels: Projects/colonymodels.md
    - WorldMaps: Projects/worldmaps.md
  - Models:
    - Math Behind the Colony Models: Models/turchin-equations.md
  name: material
  logo: assets/images/empire.svg
docs_dir: UniverseNotes
plugins:
  - search
